[core]
reloadable = true
order = 0

[package]
version = "1.0.0"
category = "Simulation"
title = "RMPflow_FES1"
description = "test1 for simplified ik"
authors = ["Isaac Sim Team"]
repository = ""
keywords = []
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"


[dependencies]
"omni.kit.uiapp" = {}
"omni.isaac.ui" = {}
"omni.isaac.core" = {}
"omni.isaac.motion_generation" = {}

[[python.module]]
name = "RmpFlow_Example_python"
